package com.smartcampusmanagmentsystem.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChatAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatAllPropertiesEquals(Chat expected, Chat actual) {
        assertChatAutoGeneratedPropertiesEquals(expected, actual);
        assertChatAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatAllUpdatablePropertiesEquals(Chat expected, Chat actual) {
        assertChatUpdatableFieldsEquals(expected, actual);
        assertChatUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatAutoGeneratedPropertiesEquals(Chat expected, Chat actual) {
        assertThat(actual)
            .as("Verify Chat auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatUpdatableFieldsEquals(Chat expected, Chat actual) {
        assertThat(actual)
            .as("Verify Chat relevant properties")
            .satisfies(a -> assertThat(a.getContactId()).as("check contactId").isEqualTo(expected.getContactId()))
            .satisfies(a -> assertThat(a.getContact()).as("check contact").isEqualTo(expected.getContact()))
            .satisfies(a -> assertThat(a.getUnreadCount()).as("check unreadCount").isEqualTo(expected.getUnreadCount()))
            .satisfies(a -> assertThat(a.getMuted()).as("check muted").isEqualTo(expected.getMuted()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getOwner()).as("check owner").isEqualTo(expected.getOwner()))
            .satisfies(a -> assertThat(a.getOwnerName()).as("check ownerName").isEqualTo(expected.getOwnerName()))
            .satisfies(a -> assertThat(a.getBinaryData()).as("check binaryData").isEqualTo(expected.getBinaryData()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatUpdatableRelationshipsEquals(Chat expected, Chat actual) {
        // empty method
    }
}
