package com.smartcampusmanagmentsystem.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GroupChatMembersAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupChatMembersAllPropertiesEquals(GroupChatMembers expected, GroupChatMembers actual) {
        assertGroupChatMembersAutoGeneratedPropertiesEquals(expected, actual);
        assertGroupChatMembersAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupChatMembersAllUpdatablePropertiesEquals(GroupChatMembers expected, GroupChatMembers actual) {
        assertGroupChatMembersUpdatableFieldsEquals(expected, actual);
        assertGroupChatMembersUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupChatMembersAutoGeneratedPropertiesEquals(GroupChatMembers expected, GroupChatMembers actual) {
        assertThat(actual)
            .as("Verify GroupChatMembers auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupChatMembersUpdatableFieldsEquals(GroupChatMembers expected, GroupChatMembers actual) {
        assertThat(actual)
            .as("Verify GroupChatMembers relevant properties")
            .satisfies(a -> assertThat(a.getGroupChatId()).as("check groupChatId").isEqualTo(expected.getGroupChatId()))
            .satisfies(a -> assertThat(a.getMemberName()).as("check memberName").isEqualTo(expected.getMemberName()))
            .satisfies(a -> assertThat(a.getMemberUserId()).as("check memberUserId").isEqualTo(expected.getMemberUserId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGroupChatMembersUpdatableRelationshipsEquals(GroupChatMembers expected, GroupChatMembers actual) {
        // empty method
    }
}
