package com.smartcampusmanagmentsystem.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModuleAllPropertiesEquals(Module expected, Module actual) {
        assertModuleAutoGeneratedPropertiesEquals(expected, actual);
        assertModuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModuleAllUpdatablePropertiesEquals(Module expected, Module actual) {
        assertModuleUpdatableFieldsEquals(expected, actual);
        assertModuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModuleAutoGeneratedPropertiesEquals(Module expected, Module actual) {
        assertThat(actual)
            .as("Verify Module auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModuleUpdatableFieldsEquals(Module expected, Module actual) {
        assertThat(actual)
            .as("Verify Module relevant properties")
            .satisfies(a -> assertThat(a.getModuleName()).as("check moduleName").isEqualTo(expected.getModuleName()))
            .satisfies(a -> assertThat(a.getModuleCode()).as("check moduleCode").isEqualTo(expected.getModuleCode()))
            .satisfies(a -> assertThat(a.getCourseId()).as("check courseId").isEqualTo(expected.getCourseId()))
            .satisfies(a -> assertThat(a.getSemester()).as("check semester").isEqualTo(expected.getSemester()))
            .satisfies(a -> assertThat(a.getLecturerId()).as("check lecturerId").isEqualTo(expected.getLecturerId()))
            .satisfies(a -> assertThat(a.getDuration()).as("check duration").isEqualTo(expected.getDuration()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModuleUpdatableRelationshipsEquals(Module expected, Module actual) {
        // empty method
    }
}
