package com.smartcampusmanagmentsystem.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResourceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceAllPropertiesEquals(Resource expected, Resource actual) {
        assertResourceAutoGeneratedPropertiesEquals(expected, actual);
        assertResourceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceAllUpdatablePropertiesEquals(Resource expected, Resource actual) {
        assertResourceUpdatableFieldsEquals(expected, actual);
        assertResourceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceAutoGeneratedPropertiesEquals(Resource expected, Resource actual) {
        assertThat(actual)
            .as("Verify Resource auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceUpdatableFieldsEquals(Resource expected, Resource actual) {
        assertThat(actual)
            .as("Verify Resource relevant properties")
            .satisfies(a -> assertThat(a.getResourceId()).as("check resourceId").isEqualTo(expected.getResourceId()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getResourceType()).as("check resourceType").isEqualTo(expected.getResourceType()))
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()))
            .satisfies(a -> assertThat(a.getCapacity()).as("check capacity").isEqualTo(expected.getCapacity()))
            .satisfies(a -> assertThat(a.getAvailability()).as("check availability").isEqualTo(expected.getAvailability()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourceUpdatableRelationshipsEquals(Resource expected, Resource actual) {
        // empty method
    }
}
